before:
  hooks:
    - go mod tidy

builds:
  - id: upgraderr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
    main: ./main.go
    binary: upgraderr

archives:
  - id: upgraderr
    builds:
      - upgraderr
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/kylesanderson/upgraderr/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ## What to do next?
    
    - Read the [documentation](https://autobrr.com)
    - Join our [Discord server](https://discord.gg/WQ2eUycxyT)

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
